nf_system:
    resource: "@NFSystemBundle/Resources/config/routing.yml"
    prefix:   /

nf_commerce:
    resource: "@NFCommerceBundle/Resources/config/routing.yml"
    prefix:   /

nf_user:
    resource: "@NFUserBundle/Resources/config/routing.yml"
    prefix:   /

