security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        NF\UserBundle\Entity\User:
            # algorithm: plaintext
            # iterations: 1
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [db_user]
        db_user:
            entity:
                class: NF\UserBundle\Entity\User
                property: name

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: nf_commerce_dashboard
            logout:
                path:   logout
                target: login
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/commerce, roles: ROLE_USER }
