# nf_commerce_homepage:
#     pattern:  /hello/{name}
#     defaults: { _controller: NFCommerceBundle:Default:index }

nf_commerce_dashboard:
    path:     /commerce/dashboard
    defaults: { _controller: NFCommerceBundle:Dashboard:index }

nf_commerce_orders:
    path:     /commerce/orders
    defaults: { _controller: NFCommerceBundle:Order:index }

nf_commerce_order_new:
    path:     /commerce/order/new
    defaults: { _controller: NFCommerceBundle:Order:new }

nf_commerce_order_edit:
    path:     /commerce/order/{id}/edit
    defaults: { _controller: NFCommerceBundle:Order:edit }

nf_commerce_order_delete:
    path:     /commerce/order/{id}/delete
    defaults: { _controller: NFCommerceBundle:Order:delete }