# nf_commerce_homepage:
#     pattern:  /hello/{name}
#     defaults: { _controller: NFCommerceBundle:Default:index }

nf_commerce_dashboard:
    path:     /commerce/dashboard
    defaults: { _controller: NFCommerceBundle:Dashboard:index }

nf_commerce_orders:
    path:     /commerce/orders
    defaults: { _controller: NFCommerceBundle:Order:index }

nf_commerce_order_new:
    path:     /commerce/orders/new
    defaults: { _controller: NFCommerceBundle:Order:new }