# nf_user_homepage:
#     pattern:  /hello/{name}
#     defaults: { _controller: NFUserBundle:Default:index }

login:
    path:     /login
    defaults: { _controller: NFUserBundle:User:login }

login_check:
    path: /login_check

logout:
    path:   /logout
