NF\UserBundle\Entity\User:
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 4
                max: 50
                minMessage: "Your name must be at least {{ limit }} characters length"
                maxMessage: "Your name cannot be longer than {{ limit }} characters length"
        email:
            - Email:
                message: The email "{{ value }}" is not a valid email.
                checkMX: true